name: Build Google Trends JSON

on:
  schedule:
    - cron: "*/30 * * * *"   # 30分ごと
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pytrends pandas
      - run: python tools/trends_build.py > trends.latest.json
      - name: Commit JSON
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add trends.latest.json
          git commit -m "Update trends JSON" || echo "No changes"
          git pushname: Build Google Trends JSON

on:
  schedule:
    - cron: "*/30 * * * *"   # 30分ごと
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pytrends pandas
      - run: python tools/trends_build.py > trends.latest.json
      - name: Commit JSON
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add trends.latest.json
          git commit -m "Update trends JSON" || echo "No changes"
          git push
